[build]
  base = "frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Optional: redirect all routes to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force fresh HTML/CSS/JS on mobile - aggressive cache busting
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"


